[project]
name = "picotcp"
version = "0.0.1"
authors = [ "Maxime Vincent <maxime.vince@gmail.com>" ]
build = "build.rs"

[lib]
name = "picotcp"
path = "src/picotcp/lib.rs"

[dependencies]
libc = "~0.2.18"
